# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
# Your code here
import numpy as np
import random

A = np.zeros((2,2))
B = np.zeros((2,2))
C = np.zeros((2,2))

def fill(matrix):
    for x in range(0, matrix.shape[0]):
        for y in range(0, matrix.shape[1]):
            matrix[x][y] = random.randrange(1, 10)
    return matrix
A = fill(A)
B = fill(B)
C = fill(C)

In [8]:
left = A.dot(B+C)
right = A.dot(B) + A.dot(C)

print(left, '\n\n', right, '\n\n', (left==right))

[[ 74.  66.]
 [160. 144.]] 

 [[ 74.  66.]
 [160. 144.]] 

 [[ True  True]
 [ True  True]]


## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [4]:
# Your code here 
left = A.dot(B.dot(C))
right = (A.dot(B)).dot(C)
print(left == right)

[[ True  True]
 [ True  True]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [7]:
# Your code here 
left = A.dot(B)
right = B.dot(A)
print(left, '\n\n', right, '\n\n', (left==right))

[[26. 32.]
 [56. 71.]] 

 [[18. 38.]
 [36. 79.]] 

 [[False False]
 [False False]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [11]:
# Your code here 
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

In [12]:
left = np.transpose(x).dot(y)
right = np.transpose(y).dot(x)
print(left, '\n\n', right, '\n\n', (left==right))

[[32]] 

 [[32]] 

 [[ True]]


## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [13]:
# Your code here 
left = np.transpose(A.dot(B))
right = np.transpose(B).dot(np.transpose(A))
print(left, '\n\n', right, '\n\n', (left==right))

[[26. 56.]
 [32. 71.]] 

 [[26. 56.]
 [32. 71.]] 

 [[ True  True]
 [ True  True]]


## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 